const { Document, Paragraph, TextRun, AlignmentType, convertInchesToTwip } = require('docx');
const fs = require('fs');

// Color for all headers
const HEADER_COLOR = "1F4E78";

// Helper function to create H1 (32pt, bold, blue)
function h1(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        bold: true,
        size: 64, // 32pt = 64 half-points
        color: HEADER_COLOR,
        font: "Arial"
      })
    ],
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create H2 (28pt, bold, blue)
function h2(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        bold: true,
        size: 56, // 28pt = 56 half-points
        color: HEADER_COLOR,
        font: "Arial"
      })
    ],
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create H3 (26pt, bold, blue)
function h3(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        bold: true,
        size: 52, // 26pt = 52 half-points
        color: HEADER_COLOR,
        font: "Arial"
      })
    ],
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create H4 (24pt, bold, blue)
function h4(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        bold: true,
        size: 48, // 24pt = 48 half-points
        color: HEADER_COLOR,
        font: "Arial"
      })
    ],
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create regular paragraph (12pt, Arial)
function p(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        size: 24, // 12pt = 24 half-points
        font: "Arial"
      })
    ],
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create bullet point
function bullet(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        size: 24, // 12pt
        font: "Arial"
      })
    ],
    bullet: {
      level: 0
    },
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create bullet with reference
function bulletWithRef(text, refNumber) {
  return new Paragraph({
    children: [
      new TextRun({
        text: text,
        size: 24,
        font: "Arial"
      }),
      new TextRun({
        text: `[${refNumber}]`,
        size: 24,
        font: "Arial",
        superScript: true
      })
    ],
    bullet: {
      level: 0
    },
    spacing: { before: 0, after: 0 }
  });
}

// Helper function to create empty line
function emptyLine() {
  return new Paragraph({
    children: [new TextRun({ text: "", size: 24 })],
    spacing: { before: 0, after: 0 }
  });
}

// Create the document
const doc = new Document({
  sections: [{
    properties: {},
    children: [
      h1("Primary Care"),
      emptyLine(),

      // USE CASE 1: Comprehensive Preventive Care Optimization
      h2("USE CASE 1: Comprehensive Preventive Care Optimization and Gap Closure"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 52-year-old patient presents for annual physical. They are due for multiple preventive services (colorectal cancer screening, mammogram, lipid screening, immunizations) but physician is uncertain which are covered, when last done, and how to coordinate scheduling across multiple facilities while addressing cost barriers."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Only 59% of eligible patients are up-to-date with colorectal cancer screening, leaving significant preventive care gaps", 1),
      bulletWithRef("Physicians must manually review previous visit notes and outside records to determine what preventive services are due", 2),
      bullet("Preventive care guidelines change frequently (USPSTF, CDC), making it difficult to stay current"),
      bullet("Insurance coverage for preventive services varies and isn't transparent at point of care"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bullet("Patients often overdue for multiple preventive services simultaneously"),
      bullet("Scheduling across multiple facilities (mammography, endoscopy, lab) is time-consuming"),
      bullet("Cost barriers prevent patients from completing recommended screening"),
      bullet("Lack of coordination leads to patients 'falling through the cracks' for follow-up"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Automated preventive care gap analysis across multiple domains: cancer screening (colonoscopy, mammogram, cervical cancer, lung CT if high-risk); cardiovascular prevention (lipid screening, BP check, aspirin if appropriate); immunizations (flu, pneumococcal, shingles, COVID-19, Tdap); screening labs (diabetes screening if risk factors, CKD screening if diabetic); behavioral health (depression screening PHQ-9, alcohol use AUDIT-C); bone health (DEXA if post-menopausal woman with risk factors); abdominal aortic aneurysm (men 65-75 with smoking history)"),
      bullet("Prioritizes gaps based on highest mortality/morbidity impact, most overdue services, and opportunities to complete multiple services efficiently"),
      bullet("Identifies patient's insurance coverage and estimated out-of-pocket costs"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bullet("Displays visual 'prevention dashboard' with traffic light system: Green (up to date); Yellow (due soon within 6 months); Red (overdue)"),
      bullet("Provides one-click ordering for all due preventive services"),
      bullet("For each service, shows: frequency recommendation (evidence grade); last completion date; patient's insurance coverage (preventive benefit vs cost-sharing); estimated out-of-pocket cost; nearby facilities accepting patient's insurance; next available appointments"),
      bullet("Flags shared decision-making discussions needed (e.g., lung cancer screening, prostate cancer screening)"),
      bullet("Generates patient-friendly explanation of benefits and importance of each service"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Automatically schedules appointments at patient-preferred facilities"),
      bullet("Submits all necessary orders to facilities"),
      bullet("Sends patient reminders (text/email/portal) before each appointment"),
      bullet("Provides preparation instructions (colonoscopy bowel prep, fasting for lipids)"),
      bullet("Triggers follow-up tracking system for results: normal results (patient notification, update prevention registry); abnormal results (alert PCP, schedule follow-up appointment)"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Early cancer detection dramatically reduces treatment costs (Stage I vs Stage IV colorectal cancer: $50K vs $200K+)", 3),
      bullet("Captures maximum quality bonuses for preventive care measures (HEDIS, MIPS stars)"),
      bullet("Reduces downstream costs from preventable disease (diabetes prevention, CV risk reduction)"),
      bullet("Optimizes facility selection balancing quality and cost"),
      bullet("Estimated financial impact: $150K-$200K annually per PCP through quality bonuses and downstream cost reduction"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Cancer screening reduces mortality by 33% when patients complete evidence-based screening (colorectal cancer with FIT testing)", 4),
      bulletWithRef("Systematic depression screening identifies mental health needs in 8-12% of adult patients", 5),
      bullet("Ensures evidence-based prevention aligned with current USPSTF guidelines"),
      bullet("Improves immunization rates preventing infectious disease complications"),
      bullet("Reduces disparities by proactively identifying gaps for all patients"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic prevention for entire patient panel, not just those who seek care frequently"),
      bullet("Reduces population-level cancer mortality through early detection"),
      bullet("Prevents progression to chronic disease (diabetes, CV disease) through risk factor management"),
      bullet("Addresses social determinants by identifying and overcoming cost barriers"),
      bullet("Estimated impact: 25-35% improvement in overall preventive service completion rates"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates time-consuming manual review of what's due"),
      bullet("'One-click' ordering of comprehensive prevention panel"),
      bullet("Automated scheduling across multiple facilities saves significant time"),
      bullet("Real-time cost information enables productive patient conversations"),
      bullet("Automatic result tracking prevents patients from 'falling through cracks'"),
      bullet("Meets quality measures effortlessly without additional documentation"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with USPSTF and CDC guideline databases with regular updates"),
      bullet("Insurance benefit verification for preventive service coverage"),
      bullet("Facility network database with appointment availability and pricing"),
      bullet("Results interface with multiple imaging and lab facilities"),
      bullet("Abnormal result alert system with PCP notification"),
      emptyLine(),

      // USE CASE 2: Diabetes Comprehensive Management
      h2("USE CASE 2: Diabetes Comprehensive Management and Complication Prevention"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 58-year-old patient with type 2 diabetes presents for follow-up with HbA1c of 8.9% on metformin and glipizide. They have hypertension and early-stage CKD (eGFR 55 mL/min/1.73m²) but have never been on a GLP-1 receptor agonist or SGLT2 inhibitor. The physician knows these medications offer cardiovascular and renal benefits but faces workflow barriers in selecting appropriate therapy, managing prior authorizations, and coordinating complication screening."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Only 70% of diabetic patients achieve HbA1c <8%, with many remaining on older, less effective medications", 6),
      bullet("Retinal exam completion rates average only 60-65% despite annual screening guidelines"),
      bullet("Complex medication selection requires understanding of cardiovascular and renal benefits beyond glycemic control"),
      bullet("Prior authorization for GLP-1 RA and SGLT2i creates 30-60 minute workflow delays per patient"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bullet("Patients face fragmented care across PCP, endocrinology, ophthalmology, nephrology, and podiatry"),
      bullet("Medication costs create adherence barriers (GLP-1 RA $800-$1,200/month without manufacturer assistance)"),
      bullet("Complications often detected late when prevention/treatment options are limited"),
      bullet("Physicians struggle to remember which patients need medication intensification vs which need specialist referral"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all diabetic patients with HbA1c >8% or suboptimal medication regimens"),
      bullet("Creates prioritized list based on cardiovascular risk, renal function, and time since last medication adjustment"),
      bullet("Pre-loads all relevant data: latest HbA1c, lipid panel, urine albumin/creatinine ratio, eGFR trends, blood pressure, retinal exam history, foot exam history"),
      bullet("Checks insurance formulary for GLP-1 RA and SGLT2i coverage with manufacturer copay assistance programs"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bullet("Displays diabetes dashboard with current status: HbA1c trend over time; medication regimen completeness; complication screening status (retinal exam, foot exam, nephropathy screening); cardiovascular risk score; target goals (HbA1c <7% or individualized, BP <130/80, LDL <70 if ASCVD)"),
      bulletWithRef("Medication recommendations based on comorbidities: GLP-1 RA if ASCVD or high CV risk (20% reduction in MACE, 0.9% HbA1c reduction); SGLT2i if CKD or heart failure (37% reduction in CKD progression)", 7),
      bullet("Flags overdue complication screening with one-click ordering: annual retinal exam; annual foot exam with monofilament testing; annual urine albumin/creatinine ratio; lipid panel"),
      bullet("Real-time prior authorization preparation with pre-populated clinical justification"),
      bullet("Shows patient-specific medication costs with manufacturer assistance programs reducing GLP-1 RA copay to $25-$50/month"),
      bullet("Specialist referral triggers: HbA1c >9% despite 3 medications → endocrinology; eGFR <30 → nephrology; abnormal retinal exam → ophthalmology; foot ulcer → podiatry/wound care"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Automatically submits prior authorization for GLP-1 RA or SGLT2i with structured clinical documentation"),
      bullet("Schedules follow-up appointments: 3 months for HbA1c recheck after medication change; annual retinal exam; annual foot exam"),
      bulletWithRef("Enrolls patient in diabetes self-management education (DSME) program shown to improve glycemic control", 8),
      bullet("Sends patient education materials on new medications, hypoglycemia recognition, and lifestyle modifications"),
      bullet("Triggers pharmacy outreach for medication adherence counseling and manufacturer copay card enrollment"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("GLP-1 RA reduces cardiovascular events by 20%, preventing $150K+ per MI/stroke avoided", 9),
      bulletWithRef("SGLT2i slows CKD progression, delaying ESRD costs of $76,969 annually per patient vs $7,537 for patients without CKD", 10),
      bullet("Diabetic retinopathy screening prevents vision loss, avoiding $30K-$60K per severe vision complication"),
      bullet("Captures quality bonuses for diabetes composite measures (HbA1c control, statin use, retinal exams, nephropathy screening)"),
      bullet("Estimated financial impact: $200K-$300K annually per PCP through complication prevention and quality bonuses"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("GLP-1 RA achieves sustained HbA1c reduction of 0.9% with weight loss up to 6.6 kg, reducing long-term complications", 11),
      bulletWithRef("SGLT2i reduces heart failure hospitalization by 26% in diabetic patients", 12),
      bulletWithRef("Annual diabetic retinopathy screening substantially reduces vision loss in working-age adults", 13),
      bullet("Systematic complication screening enables early intervention when treatment most effective"),
      bullet("Medication optimization reduces hypoglycemia risk by eliminating older sulfonylureas"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic identification of all diabetic patients with treatment gaps across entire practice"),
      bullet("Reduces disparities by ensuring all patients offered evidence-based medications regardless of insurance"),
      bullet("Improves medication adherence through cost transparency and manufacturer assistance programs"),
      bullet("Enables proactive population management with panel-level diabetes registry"),
      bullet("Estimated impact: 70-80% of diabetic patients achieving HbA1c <8%, >85% on appropriate statin, >80% annual retinal exam completion"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates cognitive burden of remembering complex medication selection algorithms"),
      bullet("Removes prior authorization frustration with automated submissions"),
      bullet("Systematic complication screening ensures no patient falls through the cracks"),
      bullet("Real-time formulary and cost information enables shared decision-making conversations"),
      bullet("Protects against malpractice by documenting guideline-concordant care"),
      bullet("Meets diabetes quality metrics effortlessly without additional documentation"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with formulary databases for real-time GLP-1 RA and SGLT2i coverage"),
      bullet("API connections to major PBMs for prior authorization automation"),
      bullet("EHR integration for seamless ordering and lab result tracking"),
      bullet("Ophthalmology and podiatry network partnerships for complication screening coordination"),
      bullet("Patient education materials and diabetes self-management program enrollment"),
      emptyLine(),

      // USE CASE 3: Chronic Kidney Disease Early Detection
      h2("USE CASE 3: Chronic Kidney Disease Early Detection and Progression Prevention"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 62-year-old patient with diabetes and hypertension presents for routine follow-up. Their eGFR has declined from 68 to 54 mL/min/1.73m² over 18 months, and urine albumin/creatinine ratio is 185 mg/g, indicating stage 3 CKD with albuminuria. The physician recognizes CKD but is uncertain about optimal medication management, when to refer to nephrology, and how to prevent progression to dialysis."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("90% of patients with early CKD are unaware of their condition; diagnosis often delayed until stage 4-5 when options are limited", 14),
      bulletWithRef("Cost progression is dramatic: $7,537 annually for no CKD to $76,969 for stages 4-5 (commercial insurance)", 15),
      bullet("Complex medication dosing adjustments based on eGFR are time-consuming and error-prone"),
      bullet("Nephrology referral criteria vary, leading to inconsistent timing and missed intervention opportunities"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bullet("Patients with CKD stages 1-3 are asymptomatic, leading to delayed diagnosis"),
      bulletWithRef("SGLT2 inhibitors proven to slow CKD progression by 37-39% but underutilized in primary care", 16),
      bullet("Medication errors common with renal dosing (metformin contraindicated if eGFR <30, NSAIDs accelerate decline)"),
      bullet("Patients unaware of dietary modifications (low-sodium, potassium management) that slow progression"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Automatically identifies all patients with declining eGFR or new albuminuria"),
      bullet("Creates prioritized list based on CKD stage, rate of progression, and diabetes/cardiovascular comorbidities"),
      bullet("Pre-loads all relevant data: eGFR trend over 6-12 months; urine albumin/creatinine ratio; electrolytes (K+, phosphorus); blood pressure trends; current medications with renal contraindications"),
      bullet("Flags medications requiring dose adjustment or discontinuation based on current eGFR"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bullet("Displays CKD dashboard with current status: CKD stage (G1-G5 based on eGFR) and albuminuria category (A1-A3); eGFR trajectory (stable vs declining); risk category (low, moderate, high, very high risk of progression)"),
      bulletWithRef("SGLT2 inhibitor recommendation for all CKD patients (diabetic and non-diabetic): dapagliflozin or empagliflozin reduce eGFR decline from -4.7 to -3.5 mL/min/1.73m²/year", 17),
      bullet("Blood pressure target: <130/80 with ACE-I or ARB as first-line (unless contraindicated)"),
      bullet("Medication safety alerts: flags metformin if eGFR <30; NSAIDs if any CKD; inappropriate doses of renally-cleared medications"),
      bullet("Nephrology referral triggers: eGFR <30 (stage 4); rapid decline (>5 mL/min/year); resistant hypertension; unexplained hematuria; refractory hyperkalemia"),
      bullet("Generates one-click orders: SGLT2i prescription with prior authorization; dietary referral (renal diet); urine albumin/creatinine follow-up in 3-6 months"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Automatically submits prior authorization for SGLT2i with structured clinical justification including CKD stage and albuminuria"),
      bullet("Schedules nephrology referral if indicated with pre-populated consultation note"),
      bullet("Sends patient education on CKD: what it means, how to slow progression, dietary modifications, medication adherence"),
      bullet("Triggers pharmacy alert to discontinue or adjust renally-cleared medications"),
      bullet("Creates follow-up reminder: 3-6 months for eGFR and electrolyte recheck after SGLT2i initiation"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("SGLT2i reduces CKD progression by 39%, delaying or preventing ESRD requiring dialysis at $76,969 annually", 18),
      bulletWithRef("Prevention of 10-15 ESRD cases per 100 CKD patients saves $2M-$5M for the health system", 19),
      bullet("Early nephrology referral enables timely vascular access planning, reducing urgent dialysis catheter costs"),
      bullet("Captures CMS quality bonuses for CKD screening and blood pressure control"),
      bullet("Estimated financial impact: $150K-$250K annually per PCP through ESRD prevention and complication avoidance"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("SGLT2i reduces composite outcome of sustained eGFR decline ≥50%, ESKD, or renal/CV death by 39% (HR 0.61)", 20),
      bullet("Automated renal dosing prevents adverse drug events from medication accumulation"),
      bullet("Early detection enables dietary and lifestyle interventions when most effective"),
      bullet("Systematic screening identifies asymptomatic CKD before irreversible damage"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic identification of all CKD patients across entire practice through automated eGFR monitoring"),
      bullet("Reduces disparities by ensuring all patients offered evidence-based SGLT2i therapy"),
      bullet("Enables proactive population management with panel-level CKD registry"),
      bullet("Timely nephrology referral improves access to transplant evaluation and pre-emptive transplant"),
      bullet("Estimated impact: 60-70% of CKD patients on SGLT2i, 30-40% reduction in CKD progression rate"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates cognitive burden of tracking eGFR trends across large patient panels"),
      bullet("Automated medication safety checks prevent renal dosing errors"),
      bullet("Clear nephrology referral criteria remove uncertainty about timing"),
      bullet("SGLT2i prior authorization automation saves 30-45 minutes per patient"),
      bullet("Protects against malpractice by documenting evidence-based CKD management"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("EHR integration to pull eGFR and albuminuria data with automated trend analysis"),
      bullet("Medication database with renal dosing adjustments for all commonly prescribed drugs"),
      bullet("Nephrology referral workflow with templated consultation requests"),
      bullet("Patient portal integration for CKD education and dietary resources"),
      emptyLine(),

      // USE CASE 4: Polypharmacy Optimization
      h2("USE CASE 4: Polypharmacy Optimization and Deprescribing in Older Adults"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 78-year-old patient presents for follow-up on 14 medications. They've had two falls in the past 6 months, complain of dizziness and dry mouth, and report difficulty affording medications. Their medication list includes three anticholinergic drugs (diphenhydramine for sleep, oxybutynin for overactive bladder, amitriptyline for neuropathy), a benzodiazepine (lorazepam), and duplicate antihypertensives causing hypotension."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Polypharmacy (≥5 medications) affects >40% of older adults and is a leading cause of adverse drug reactions", 21),
      bulletWithRef("Beers Criteria lists potentially inappropriate medications (PIMs) in older adults, but manual review is time-consuming", 22),
      bullet("Anticholinergic burden and fall risk difficult to calculate without automated tools"),
      bullet("Deprescribing requires complex risk-benefit analysis that's challenging in busy primary care"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bulletWithRef("Anticholinergic drugs increase fall risk: each Level 2 drug increases fall/injury hazard by 56% (HR 1.56)", 23),
      bulletWithRef("Hip fracture costs $30,000-$60,000 per event with significant mortality and morbidity", 24),
      bullet("Medication costs create financial strain, leading to non-adherence to essential medications"),
      bullet("Polypharmacy causes cognitive impairment, functional decline, and reduced quality of life"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all patients age ≥65 on ≥5 medications or with fall history"),
      bullet("Creates prioritized list based on number of PIMs, anticholinergic burden score, recent falls, and medication cost burden"),
      bullet("Pre-loads complete medication history including over-the-counter and supplements"),
      bullet("Calculates anticholinergic cognitive burden (ACB) score automatically"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bulletWithRef("Displays medication safety dashboard: total medication count; Beers Criteria PIMs identified; anticholinergic burden score (ACB 0 = none, 1 = mild, 2-3 = moderate, >3 = severe); fall risk score; estimated monthly medication costs", 25),
      bullet("Highlights specific PIMs with safer alternatives: diphenhydramine → melatonin or trazodone for sleep; oxybutynin → mirabegron (non-anticholinergic); amitriptyline → gabapentin or duloxetine; benzodiazepines → taper protocol with CBT referral; PPIs long-term → consider discontinuation trial"),
      bullet("Deprescribing recommendations with evidence: medications to discontinue entirely; medications to dose-reduce; safer alternatives; estimated fall risk reduction"),
      bullet("Cost savings calculation showing monthly savings from deprescribing or switching to generics"),
      bullet("One-click deprescribing orders with patient-friendly taper schedules"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Generates patient-friendly deprescribing plan with rationale for each change"),
      bullet("Sends pharmacy alert to discontinue medications and counsel patient on changes"),
      bullet("Schedules follow-up in 2-4 weeks to assess tolerance and monitor for withdrawal symptoms"),
      bullet("Triggers fall prevention program referral (physical therapy, home safety evaluation)"),
      bullet("Creates medication reconciliation alert for next visit to reassess regimen"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Prevention of falls/fractures: reducing PIMs by 50% can prevent hip fractures costing $30K-$60K per event", 26),
      bulletWithRef("Adverse drug events cost $7,000-$15,000 per event; deprescribing reduces ADE rate by 30-40%", 27),
      bullet("Medication cost savings: $200-$400 per patient annually from discontinuing unnecessary medications"),
      bullet("Reduces hospitalizations from drug-related adverse events by 20-30%"),
      bullet("Estimated financial impact: $80K-$120K saved per 100 older adults through fall/fracture prevention and ADE reduction"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Reducing anticholinergic burden improves cognitive function and reduces delirium risk", 28),
      bulletWithRef("Deprescribing PIMs reduces fall risk by 30-50% in high-risk older adults", 29),
      bullet("Systematic medication review prevents drug-drug interactions and duplicate therapy"),
      bullet("Improved medication affordability increases adherence to essential medications (statins, antihypertensives)"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic identification of all older adults with polypharmacy across entire practice"),
      bullet("Reduces health disparities by addressing medication cost barriers"),
      bullet("Enables proactive panel management with automated PIM screening"),
      bullet("Improves functional status and quality of life through fall prevention and reduced side effects"),
      bullet("Estimated impact: 30-50% reduction in PIMs, 25-40% reduction in fall-related injuries"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates time-consuming manual Beers Criteria review with automated PIM identification"),
      bullet("Provides evidence-based deprescribing recommendations removing guesswork"),
      bullet("Reduces medico-legal risk by documenting systematic medication safety review"),
      bullet("Improves patient satisfaction through reduced medication burden and costs"),
      bullet("Simplifies complex polypharmacy management with actionable recommendations"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with Beers Criteria database with annual updates"),
      bullet("Anticholinergic burden calculator with validated scoring system"),
      bullet("Pharmacy integration for medication discontinuation and patient counseling"),
      bullet("Fall risk assessment tools and physical therapy referral protocols"),
      emptyLine(),

      // USE CASE 5: Social Determinants of Health
      h2("USE CASE 5: Social Determinants of Health Identification and Community Resource Linkage"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 45-year-old patient with diabetes and hypertension has missed three appointments in the past 6 months and HbA1c has risen from 7.2% to 9.8%. They report inconsistent medication adherence due to cost but seem hesitant to discuss other challenges. The physician suspects social factors are impacting health but lacks time for comprehensive screening and knowledge of available community resources."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Social determinants of health (SDOH) account for 50% of health outcomes vs only 20% for clinical care, yet screening remains inconsistent", 30),
      bullet("Physicians lack structured tools to identify food insecurity, housing instability, transportation barriers, and financial strain"),
      bullet("Even when SDOH needs identified, connecting patients to resources is fragmented and time-consuming"),
      bullet("No closed-loop tracking to confirm patients received services or if needs were met"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bulletWithRef("Children at risk for food insecurity are 56% more likely to be in fair/poor health and 60% more likely to have developmental delays", 31),
      bullet("Transportation barriers lead to missed appointments and medication non-adherence"),
      bullet("Patients reluctant to disclose social needs due to stigma or belief that physician can't help"),
      bullet("Complex process of finding and accessing community resources creates insurmountable barriers"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies patients with red flags for SDOH needs: frequent missed appointments; medication non-adherence patterns; uncontrolled chronic diseases despite appropriate therapy; geographic residence in high-need areas"),
      bullet("Pre-loads previous SDOH screening results if available"),
      bullet("Prepares standardized screening tool (PRAPARE, AHC, or Hunger Vital Sign)"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bulletWithRef("Displays integrated SDOH screening questionnaire: food insecurity (Hunger Vital Sign: 2-item validated screen); housing instability; transportation barriers; utility shut-off risk; financial resource strain; safety concerns; social isolation", 32),
      bullet("Real-time identification of local community resources based on ZIP code: food banks and SNAP enrollment assistance; housing assistance programs; free/low-cost transportation (Lyft/Uber Health integration); utility assistance programs; prescription assistance programs"),
      bullet("One-click referrals to community health workers or social work for complex needs"),
      bullet("Generates patient-friendly resource list with contact information, hours, eligibility criteria"),
      bullet("Flags patients eligible for enhanced care management programs or Medicaid SDOH benefits"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Automatically sends resource information to patient via text/email/portal in preferred language"),
      bullet("Creates referrals to community-based organizations with integrated platforms (UniteUs, NowPow, Aunt Bertha)"),
      bullet("Triggers community health worker outreach for high-need patients"),
      bullet("Schedules follow-up in 1-3 months to reassess SDOH needs and confirm resource connection"),
      bullet("Tracks closed-loop: did patient connect with resource? Was need addressed?"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bullet("Addressing food insecurity and transportation barriers improves medication adherence by 40-60%, reducing hospitalizations"),
      bullet("Housing stability interventions reduce ED visits by 20-30% and admissions by 15-25%"),
      bullet("SDOH screening and intervention billable under certain circumstances (G-codes for social determinant risk assessment)"),
      bullet("Value-based contracts increasingly reward SDOH screening and intervention"),
      bullet("Estimated financial impact: $120K-$180K saved per 100 high-need patients through hospitalization and ED visit reduction"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Addressing SDOH improves chronic disease control: 20-35% improvement in diabetes HbA1c and hypertension control when food security and medication access ensured", 33),
      bullet("Transportation assistance reduces missed appointments by 30-50%, enabling consistent preventive care"),
      bullet("Food security interventions reduce risk of hypoglycemia in diabetic patients on insulin"),
      bullet("Social isolation screening enables mental health referrals and suicide prevention"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic SDOH screening across entire patient population identifies previously hidden needs"),
      bullet("Addresses root causes of health disparities in underserved communities"),
      bullet("Community resource linkage strengthens health system-community partnerships"),
      bullet("Longitudinal tracking enables measurement of intervention effectiveness"),
      bullet("Estimated impact: 60-70% of identified SDOH needs successfully addressed through resource linkage"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Structured screening tool makes SDOH assessment quick and non-stigmatizing"),
      bullet("Eliminates burden of knowing all community resources with automated, ZIP code-specific recommendations"),
      bullet("One-click referrals save time compared to manual resource navigation"),
      bullet("Closed-loop tracking provides accountability and feedback on patient outcomes"),
      bullet("Improves patient trust and therapeutic relationship by addressing whole-person needs"),
      bullet("Meets emerging quality metrics for SDOH screening in value-based contracts"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with community resource platforms (UniteUs, NowPow, Aunt Bertha, findhelp.org)"),
      bullet("Multilingual screening tools and resource directories"),
      bullet("Community health worker or social work partnerships for complex cases"),
      bullet("Patient portal integration for secure resource sharing"),
      bullet("Data analytics to track SDOH prevalence and intervention effectiveness"),
      emptyLine(),

      // USE CASE 6: Colonoscopy Referral Retention
      h2("USE CASE 6: Colonoscopy Referral Retention and Screening Completion"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 52-year-old patient is due for colorectal cancer screening. The physician recommends colonoscopy and begins searching for available gastroenterologists, but is unsure whether in-network GI has availability, how long the wait is, or if patient can afford the procedure. The patient leaves with a vague plan to \"schedule somewhere\" but the referral goes unfulfilled."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Only 59% of eligible patients (age 45-75) are up-to-date with colorectal cancer screening, leaving millions at risk", 34),
      bullet("Screening colonoscopy referrals frequently leak to out-of-network facilities due to access barriers and patient convenience"),
      bullet("Long wait times for in-network GI (often 3-6 months) lead patients to seek faster external options"),
      bullet("Lost referral revenue and downstream pathology/treatment opportunities"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bullet("Patients given referral but left to navigate scheduling, creating friction and abandonment"),
      bullet("Confusion about different screening options (colonoscopy vs FIT vs Cologuard)"),
      bulletWithRef("Positive FIT tests require colonoscopy within 6 months; without outreach, many patients never complete diagnostic evaluation", 35),
      bullet("Cost uncertainty creates hesitation (screening colonoscopy fully covered, but what if polyps found?)"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all patients age 45-75 due for colorectal cancer screening (never screened, >10 years since last colonoscopy, >1 year since FIT, >3 years since Cologuard)"),
      bullet("Creates prioritized list based on age, family history, and time overdue"),
      bullet("Checks real-time GI schedule for \"Direct Access Colonoscopy\" slots (no pre-procedure GI visit needed for average-risk screening)"),
      bullet("Pre-loads insurance coverage information for colonoscopy and alternative screening modalities"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bullet("Displays colorectal cancer screening dashboard: patient's screening status; recommended screening modality based on risk factors; family history of colorectal cancer or polyps; previous screening results"),
      bullet("Shared decision-making tool comparing options: colonoscopy (gold standard, 10-year interval if normal); FIT (annual, sent home, requires follow-up colonoscopy if positive); Cologuard (stool DNA test, 3-year interval, higher false positive rate)"),
      bulletWithRef("If colonoscopy chosen, shows 'In-Network GI Access': available Direct Access Colonoscopy slots within 2-4 weeks at health system endoscopy centers; patient out-of-pocket cost estimate (typically $0 for screening); contrast with unknown external referral wait time", 36),
      bullet("One-click generates referral, holds appointment slot, and prints bowel prep instructions immediately"),
      bullet("Eliminates need for separate pre-procedure GI consult visit, saving patient time and copay"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Automatically schedules colonoscopy appointment and sends confirmation to patient"),
      bullet("Sends prep instructions and pre-procedure dietary restrictions 1 week before procedure"),
      bullet("Reminder calls/texts 48 hours before procedure to reduce no-shows"),
      bullet("For FIT or Cologuard orders: ships test to patient's home with instructions; triggers outreach if test not returned in 30 days; if positive, automatically schedules colonoscopy and alerts PCP"),
      bullet("Tracks completion rates and triggers outreach for patients who don't complete screening"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Retaining colonoscopy referrals in-network captures procedural revenue plus downstream pathology and treatment", 37),
      bulletWithRef("Early colorectal cancer detection dramatically reduces treatment costs (Stage I: $50K vs Stage IV: $200K+)", 38),
      bullet("Captures quality bonuses for colorectal cancer screening rates (HEDIS, MIPS, MSSP measures)"),
      bullet("Direct Access Colonoscopy reduces no-show rates from 15-20% to 5-8% through streamlined scheduling"),
      bullet("Estimated financial impact: $100K-$150K annually per PCP through referral retention and quality bonuses"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Patients with at least one FIT test in prior 5 years are 33% less likely to die from colorectal cancer", 39),
      bullet("Colonoscopy enables removal of precancerous polyps before cancer develops"),
      bullet("Direct Access pathway reduces time from decision to procedure, improving screening completion"),
      bullet("Automated follow-up for positive FIT/Cologuard prevents loss to follow-up"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic screening increases population-level colorectal cancer screening rates from 59% to 75-85%"),
      bullet("Reduces colorectal cancer mortality through early detection when treatment most effective"),
      bullet("Addresses disparities by reducing access barriers (cost, scheduling complexity, transportation)"),
      bullet("Longitudinal tracking enables panel-level monitoring of screening gaps"),
      bullet("Estimated impact: 25-40% improvement in colorectal cancer screening completion rates"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates time spent searching for GI availability and navigating referral systems"),
      bullet("One-click referral with immediate scheduling improves workflow efficiency"),
      bullet("Real-time GI access information enables confident patient conversations"),
      bullet("Automated tracking ensures patients complete screening without manual follow-up"),
      bullet("Meets colorectal cancer screening quality metrics effortlessly"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with GI scheduling system for real-time Direct Access slot availability"),
      bullet("Direct Access Colonoscopy protocols for average-risk screening (no pre-procedure GI visit required)"),
      bullet("FIT and Cologuard ordering integration with home delivery logistics"),
      bullet("Automated outreach platform for test completion and abnormal result follow-up"),
      emptyLine(),

      // USE CASE 7: Lower Back Pain Imaging Stewardship
      h2("USE CASE 7: Lower Back Pain Imaging Stewardship and Physical Therapy First"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 38-year-old patient presents with acute lower back pain for 10 days after helping a friend move. They request an MRI to \"see what's wrong.\" There are no red flags (no fever, no neurological deficits, no trauma, no history of cancer). The physician knows imaging is not indicated but faces patient expectations, uncertainty about what to offer instead, and concern about missing something serious."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("31% of lumbar spine MRIs are classified as inappropriate per CMS criteria, contributing to unnecessary healthcare costs", 40),
      bulletWithRef("Early imaging increases 1-year costs by $4,700 per patient with no improvement in outcomes", 41),
      bullet("Choosing Wisely campaign identifies imaging for uncomplicated low back pain as a top target for quality improvement"),
      bullet("Difficulty tracking which patients received inappropriate imaging for quality reporting"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bullet("Patients expect imaging to diagnose back pain, creating pressure on physicians to order MRI"),
      bulletWithRef("MRI findings (bulging discs, degenerative changes) are often incidental and unrelated to symptoms, leading to unnecessary interventions", 42),
      bullet("Patient out-of-pocket costs for MRI: $800-$1,500 vs physical therapy copay: $30-$50"),
      bullet("Insurance denials for inappropriate imaging create delays and patient frustration"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all patients scheduled with low back pain chief complaint"),
      bullet("Pre-loads red flag checklist and imaging history"),
      bullet("Checks availability for \"Fast Track Physical Therapy\" with expedited appointments (within 48-72 hours)"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bulletWithRef("Displays red flag assessment: fever/chills; unexplained weight loss; history of cancer; age >70 with minor trauma or age >50 with significant trauma; progressive neurological deficit; saddle anesthesia; bowel/bladder dysfunction; duration >6 weeks", 43),
      bullet("If no red flags present, recommendation: conservative management pathway (NSAIDs, activity modification, physical therapy) for 6 weeks before imaging"),
      bulletWithRef("Shows patient education: 'MRI findings in people WITHOUT back pain: 30% have disc bulges by age 30, 60% by age 50, 84% by age 80 - most are normal aging, not the cause of pain'", 44),
      bullet("Cost comparison display: lumbar MRI $1,200-$2,500 with $800+ patient copay vs physical therapy $150-$300 with $30-$50 copay; insurance denial risk for MRI <6 weeks"),
      bullet("One-click orders: 'Fast Track PT' with appointment within 48-72 hours; NSAIDs or muscle relaxants; return-to-work note with activity modifications"),
      bullet("One-click inserts 'Red Flag Absence Documentation' into note to support medical decision-making and protect against medico-legal risk"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Schedules physical therapy appointment with expedited access"),
      bullet("Sends patient education materials: natural history of low back pain (90% resolve in 6 weeks); home exercises and stretching; activity modification guidance; when to return (red flags develop)"),
      bullet("Triggers follow-up at 4-6 weeks: if improved, continue conservative care; if no improvement or red flags, consider imaging"),
      bullet("Tracks outcomes: pain improvement, functional status, imaging utilization, patient satisfaction"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Physical therapy first reduces 1-year total costs by $4,700 per patient compared to early imaging pathway", 45),
      bulletWithRef("Reduces odds of surgery, injections, specialist visits, and ED visits within 1 year", 46),
      bullet("Decreases insurance denials and appeals, saving 20-30 minutes of staff time per avoided denial"),
      bullet("Captures quality bonuses for adherence to Choosing Wisely guidelines"),
      bullet("Estimated financial impact: $60K-$90K annually per PCP through avoided inappropriate imaging and downstream interventions"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Meta-analysis of 6 RCTs (1,804 patients): NO differences in pain, function, quality of life, or overall improvement between routine imaging vs usual care", 47),
      bullet("Avoids radiation exposure from CT scans and reduces incidental findings requiring unnecessary follow-up"),
      bullet("Physical therapy improves functional outcomes and prevents chronicity of low back pain"),
      bullet("Red flag documentation protects against missing serious pathology (cauda equina, malignancy, infection)"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic application of evidence-based guidelines across entire patient population"),
      bullet("Reduces low-value care utilization at population level"),
      bullet("Improves patient education about natural history of low back pain, reducing future healthcare-seeking for self-limited episodes"),
      bullet("Enables tracking of imaging appropriateness rates for quality improvement"),
      bullet("Estimated impact: 40-50% reduction in inappropriate lumbar spine imaging"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Removes pressure to order imaging by providing evidence-based alternative and patient education tools"),
      bullet("Real-time cost information enables shared decision-making conversations"),
      bullet("Fast Track PT access addresses patient concerns with immediate action plan"),
      bullet("Automated red flag documentation protects against medico-legal risk"),
      bullet("Meets Choosing Wisely quality metrics without additional work"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Physical therapy partnership with expedited appointment access (Fast Track PT slots)"),
      bullet("Patient education materials on natural history of low back pain and imaging findings"),
      bullet("EHR integration for red flag assessment and decision support"),
      bullet("Quality tracking dashboard for imaging appropriateness rates"),
      emptyLine(),

      // USE CASE 8: HCC Coding Optimization
      h2("USE CASE 8: HCC Coding Optimization and Risk Adjustment Accuracy"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 72-year-old Medicare Advantage patient presents for annual wellness visit with chronic conditions including diabetes with neuropathy, COPD, and heart failure. The physician manages these conditions but codes only \"diabetes\" without specifying complications. The patient's RAF (Risk Adjustment Factor) score remains artificially low, underestimating their complexity and underpayment for their care."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("$377 million lost annually from HCC coding inaccuracies and missed risk adjustment opportunities", 48),
      bulletWithRef("RADV audits extrapolate findings across entire population: every $1 of overpayment becomes $55 in penalties", 49),
      bullet("Chronic conditions must be recaptured annually or they drop off RAF calculations, requiring systematic documentation"),
      bullet("Physicians unfamiliar with HCC coding specificity requirements and MEAT criteria (Monitored, Evaluated, Assessed, Treated)"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bulletWithRef("RAF score 1.0 = average predicted costs; higher RAF = more complex/costly patients deserving higher capitation payments", 50),
      bullet("Undercoding underestimates patient complexity, leading to inadequate resources for care management"),
      bullet("Vague documentation (\"diabetes\") vs specific coding (\"diabetes with diabetic peripheral neuropathy, E11.40\") misses HCC capture"),
      bullet("Annual physician or APP visit required to recapture chronic HCCs; specialist visits don't count"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all Medicare Advantage patients with HCC gaps or recapture needs"),
      bullet("Creates prioritized list based on: suspected HCCs (conditions discussed but not coded); prior year HCCs needing annual recapture; chronic conditions without specific ICD-10 codes"),
      bullet("Pre-loads problem list, previous year's HCC diagnoses, and specialty visit notes mentioning chronic conditions"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bulletWithRef("Displays HCC dashboard: current RAF score vs expected based on complexity; HCCs captured year-to-date vs prior year; 'Recapture List' of chronic conditions from last year needing documentation this year; 'Coding Specificity Opportunities' where more specific ICD-10 codes apply", 51),
      bullet("Real-time coding suggestions during documentation: 'Diabetes and neuropathy discussed. Consider E11.40 (Type 2 DM with diabetic neuropathy) instead of E11.9 (Type 2 DM without complications)'; 'CHF mentioned. Specify systolic vs diastolic and acute vs chronic for accurate HCC'"),
      bullet("MEAT criteria helper: one-click inserts documentation phrases supporting HCC codes: 'Diabetes with neuropathy: Monitored with HbA1c and monofilament exam. Evaluated current glycemic control. Assessed medication adherence. Treated with metformin and gabapentin for neuropathic pain'"),
      bullet("One-click adds diagnoses to Assessment & Plan with appropriate specificity"),
      bullet("Alerts for conditions needing annual encounter (specialist notes don't count for RAF)"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Validates that all discussed chronic conditions have been coded with appropriate specificity"),
      bullet("Generates HCC recapture report for quality assurance and revenue cycle review"),
      bullet("Schedules follow-up for patients with multiple HCC gaps requiring additional visits"),
      bullet("Tracks RAF score changes and estimated revenue impact"),
      bullet("Creates alerts for conditions needing recapture before year-end"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Accurate HCC coding increases capitation payments reflecting true patient complexity (average $10K-$15K additional revenue per PCP panel annually)", 52),
      bulletWithRef("Avoids RADV penalties where every dollar of inaccuracy multiplies 55x across population", 53),
      bullet("Higher RAF scores enable enhanced care management resources for complex patients"),
      bullet("Supports accurate cost predictions for Medicare Shared Savings Program (MSSP) ACOs"),
      bullet("Estimated financial impact: $100K-$200K annually per PCP through accurate risk adjustment and avoided penalties"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bullet("Accurate documentation of patient complexity enables appropriate care management resources"),
      bullet("Systematic review of chronic conditions ensures nothing is overlooked or under-managed"),
      bullet("Improved problem list accuracy enhances care coordination and medication reconciliation"),
      bullet("MEAT criteria documentation demonstrates quality of chronic disease management"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic HCC recapture ensures all Medicare Advantage patients receive annual comprehensive assessment"),
      bullet("Higher RAF scores trigger care management programs for complex patients"),
      bullet("Improved documentation enables better population health analytics and risk stratification"),
      bullet("Reduces disparities by ensuring all patients' complexity is accurately recognized"),
      bullet("Estimated impact: 20-30% increase in HCC capture rate, 0.15-0.25 point RAF score improvement per patient"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates cognitive burden of remembering HCC coding rules and ICD-10 specificity"),
      bullet("Real-time coding suggestions during documentation save time and improve accuracy"),
      bullet("MEAT criteria helper automates documentation requirements"),
      bullet("Protects against RADV audits through compliant, specific documentation"),
      bullet("Demonstrates physician's value in managing complex patient populations"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with HCC coding databases and annual updates"),
      bullet("NLP analysis of documentation to identify mentioned but uncoded conditions"),
      bullet("Revenue cycle management partnership for HCC validation and reporting"),
      bullet("Physician education on HCC coding principles and MEAT criteria"),
      emptyLine(),

      // USE CASE 9: Pre-operative Clearance Optimization
      h2("USE CASE 9: Pre-operative Risk Stratification and Clearance Optimization"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 68-year-old patient with hypertension and diabetes is scheduled for elective hip replacement in 3 weeks. The surgeon requests \"cardiac clearance.\" The physician is uncertain which tests are needed (EKG? stress test? echo?), how to calculate cardiac risk, and whether the patient can safely proceed with surgery. The patient is anxious and the surgical scheduler is pressing for clearance documentation."),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bullet("Pre-operative clearance requests are frequent but guidelines are complex and vary by surgery type"),
      bulletWithRef("Conceptual shift: NOT 'cardiac clearance' but rather 'risk stratification and mitigation' to optimize perioperative outcomes", 54),
      bullet("Unnecessary testing (stress tests, echos) delays surgery without improving outcomes"),
      bullet("Missing required tests leads to OR cancellations costing $1,500-$10,000 per case plus patient/surgeon frustration"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bulletWithRef("Revised Cardiac Risk Index (RCRI) predicts perioperative cardiac complications: 0 factors = 0.4% risk; 1 factor = 0.9%; 2 factors = 6.6%; ≥3 factors = 11% risk", 55),
      bullet("Patients on anticoagulation need bridge therapy guidance (when to stop, when to restart)"),
      bullet("Anesthesia groups have specific requirements that vary by hospital/surgery center"),
      bullet("Communication gaps between PCP, surgeon, and anesthesia lead to missing information and delays"),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all patients with upcoming surgeries requiring pre-operative assessment"),
      bullet("Pre-loads surgery type, patient comorbidities, current medications, and recent labs/tests"),
      bullet("Retrieves specific anesthesia requirements for the surgical center (e.g., K+ within 7 days, EKG within 30 days for patients >65)"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bulletWithRef("Automatic RCRI calculation based on 6 factors: high-risk surgery (intrathoracic, intraperitoneal, suprainguinal vascular); ischemic heart disease history; heart failure history; cerebrovascular disease history; preop insulin therapy; creatinine >2 mg/dL", 56),
      bullet("Risk-based testing recommendations: Low risk (RCRI 0-1) → NO additional testing, proceed to surgery; Intermediate risk (RCRI 2) → consider functional capacity assessment; High risk (RCRI ≥3) → consider cardiology consultation, optimize medical therapy"),
      bullet("Pre-operative checklist customized to surgery and anesthesia requirements: required labs (CBC, BMP, coags if needed); required imaging (CXR for thoracic surgery); medication management (hold metformin morning of surgery, continue beta-blockers); anticoagulation bridge plan if applicable"),
      bullet("Flags missing requirements with one-click ordering: 'Missing: Potassium level within 7 days' → one-click BMP order; 'Missing: EKG within 30 days for age >65' → one-click EKG order"),
      bullet("Anticoagulation bridge protocol: for patients on warfarin/DOACs, generates specific instructions (stop warfarin 5 days before, bridge with enoxaparin if high VTE risk, check INR day before surgery)"),
      bullet("One-click inserts 'Cleared for Surgery' template addressing surgeon/anesthesia requirements"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Orders all missing labs/tests identified in pre-op checklist"),
      bullet("Sends clearance letter to surgeon and anesthesia with RCRI score, optimization plan, and test results"),
      bullet("Patient education: medication instructions (what to take, what to hold), fasting instructions, when to arrive"),
      bullet("Creates alert: if new labs show abnormality (e.g., hypokalemia), notify PCP before surgery"),
      bullet("Tracks OR cancellation rates due to inadequate pre-op workup"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bullet("Prevents costly OR cancellations ($1,500-$10,000 per case) due to incomplete workup or abnormal labs discovered day-of-surgery"),
      bullet("Reduces unnecessary testing (stress tests for low-risk patients) saving $1,500-$3,000 per avoided test"),
      bullet("Optimized perioperative medical management reduces post-operative complications by 20-30%"),
      bullet("Improved surgical throughput by preventing delays and rescheduling"),
      bullet("Estimated financial impact: $80K-$150K annually per PCP through reduced cancellations and avoided unnecessary testing"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("RCRI-based risk stratification prevents both under-testing (missing high-risk patients) and over-testing (unnecessary stress tests in low-risk patients)", 57),
      bulletWithRef("Even for elective procedures, noninvasive stress testing has dubious role; preoperative revascularization hasn't shown reduction in perioperative cardiac complications", 58),
      bullet("Anticoagulation bridge protocols prevent perioperative bleeding and thrombotic complications"),
      bullet("Systematic checklist ensures all anesthesia requirements met, reducing day-of-surgery surprises"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Standardized risk assessment across all pre-operative patients"),
      bullet("Enables tracking of perioperative outcomes and continuous quality improvement"),
      bullet("Reduces delays to necessary surgery, improving access and patient satisfaction"),
      bullet("Data-driven conversations with surgeons/anesthesia about testing requirements"),
      bullet("Estimated impact: 50-70% reduction in OR cancellations due to incomplete pre-op workup"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Eliminates uncertainty about which tests are needed with surgery-specific checklists"),
      bullet("Automated RCRI calculation removes mental math and guideline memorization"),
      bullet("One-click clearance templates save 10-15 minutes per pre-op visit"),
      bullet("Reduces phone calls and rework from missing information"),
      bullet("Protects against medico-legal risk by documenting systematic risk assessment"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with surgical scheduling systems to identify upcoming surgeries"),
      bullet("Anesthesia group-specific requirement databases (varies by hospital/surgery center)"),
      bullet("EHR integration for automated RCRI calculation and order entry"),
      bullet("Anticoagulation bridge protocols and patient education materials"),
      emptyLine(),

      // USE CASE 10: Generic/Biosimilar Therapeutic Interchange
      h2("USE CASE 10: Generic/Biosimilar Therapeutic Interchange and Cost Savings"),
      emptyLine(),

      h3("Clinical Scenario"),
      emptyLine(),
      p("A 55-year-old patient with rheumatoid arthritis is on adalimumab (Humira) costing $6,000 per month with $400 patient copay. An interchangeable biosimilar (Cyltezo) is now available at 60% lower cost with $50 copay, but the physician is uncertain about biosimilar safety, efficacy, and the switching process. The patient is hesitant due to concerns about \"switching to a different medication.\""),
      emptyLine(),

      h3("Current State Challenges"),
      emptyLine(),
      h4("At a practice level:"),
      emptyLine(),
      bulletWithRef("Biosimilars have generated $56 billion in healthcare savings since 2015, with $20 billion saved in 2024 alone", 59),
      bullet("Despite proven safety and efficacy, biosimilar adoption remains low due to physician/patient unfamiliarity and switching inertia"),
      bullet("Therapeutic interchange opportunities extend beyond biologics to branded vs generic drugs (inhalers, PPIs, antidepressants)"),
      bullet("Manual formulary navigation is time-consuming and patient copays often unknown at point of prescribing"),
      emptyLine(),

      h4("At the individual patient level:"),
      emptyLine(),
      bulletWithRef("Biosimilars are 50-60% cheaper than reference biologics at launch with NO clinically meaningful differences in efficacy/safety", 60),
      bulletWithRef("Interchangeability designation means biosimilars can be substituted without consulting prescriber (like generic drugs)", 61),
      bulletWithRef("Lower copayments improve adherence: VHA and Kaiser Permanente saw 80% adherence improvement with interchange programs vs 3.2% average", 62),
      bullet("Patients confused about biosimilar vs generic vs \"different medication\""),
      emptyLine(),

      h3("Cordance Solution"),
      emptyLine(),
      h4("Before Encounter"),
      emptyLine(),
      bullet("Identifies all patients on high-cost branded medications with available generic or biosimilar alternatives"),
      bullet("Creates prioritized list based on: highest patient copay savings; greatest system cost savings; interchangeable biosimilars vs therapeutically equivalent alternatives"),
      bullet("Checks patient-specific formulary for coverage and tier placement"),
      emptyLine(),

      h4("During Encounter"),
      emptyLine(),
      bullet("Real-time formulary optimization alerts: 'Switch Symbicort (fluticasone/formoterol) to Wixela? Saves patient $150/month'; 'Switch Humira (adalimumab) to Cyltezo (interchangeable biosimilar)? Saves patient $350/month and health system $2,400/month'"),
      bullet("Displays comparison: current medication (brand name, copay, tier); alternative (generic/biosimilar name, copay, tier); evidence of therapeutic equivalence or interchangeability; patient cost savings (monthly and annually); system cost savings"),
      bulletWithRef("Biosimilar education: 'Biosimilars are highly similar to original biologic with NO clinically significant differences in efficacy/safety. Approved through comprehensive analytical, preclinical, and clinical trials'", 63),
      bullet("Shows local pharmacy availability: which pharmacies stock the alternative medication"),
      bullet("One-click switch: discontinues old prescription, orders new one with appropriate quantity/refills"),
      bullet("Generates patient-friendly explanation: 'We are switching you to a medication that works the same but costs less'"),
      emptyLine(),

      h4("After Encounter"),
      emptyLine(),
      bullet("Sends prescription to patient's preferred pharmacy (or specialty pharmacy if biologic)"),
      bullet("Pharmacy notification of therapeutic interchange with education for patient counseling"),
      bullet("Patient education materials on biosimilars/generics with FAQ addressing safety concerns"),
      bullet("Follow-up alert at 30-60 days to confirm tolerance and adherence"),
      bullet("Tracks cost savings at patient and population level"),
      emptyLine(),

      h3("Impact on Three Pillars"),
      emptyLine(),
      h4("Economics (Value-Based Care & Fee-for-Service)"),
      emptyLine(),
      bulletWithRef("Biosimilars average 50-60% cost savings vs reference biologics, translating to $2,000-$4,000 per patient annually", 64),
      bullet("Generic substitutions save $200-$400 per patient annually across common medication classes"),
      bullet("Improved medication affordability increases adherence, reducing downstream hospitalizations and complications"),
      bullet("Health system captures margin on internal specialty pharmacy dispensing"),
      bullet("Estimated financial impact: $100K-$180K annually per PCP through therapeutic interchange across patient panel"),
      emptyLine(),

      h4("Quality & Safety"),
      emptyLine(),
      bulletWithRef("Biosimilars demonstrate NO clinically significant differences from reference products in rigorous comparative trials", 65),
      bulletWithRef("Interchangeable biosimilars meet additional FDA standards for switching studies", 66),
      bullet("Improved medication adherence through reduced cost barriers leads to better disease control"),
      bullet("Generic medications are bioequivalent to brand-name counterparts by FDA requirement"),
      emptyLine(),

      h4("Population Health & Outcomes"),
      emptyLine(),
      bullet("Systematic identification of high-cost medication users across entire patient panel"),
      bullet("Reduces health disparities by addressing medication affordability barriers"),
      bulletWithRef("80% adherence improvement when cost barriers removed through interchange programs", 67),
      bullet("Population-level tracking of biosimilar adoption and cost savings"),
      bullet("Estimated impact: 60-75% conversion rate to biosimilars/generics among eligible patients, $500K-$1M annual savings per 1,000-patient panel"),
      emptyLine(),

      h4("Physician Value Proposition"),
      emptyLine(),
      bullet("Real-time formulary information eliminates guesswork about coverage and copays"),
      bullet("One-click switching saves time compared to manual prescription changes"),
      bullet("Patient education tools address biosimilar safety concerns proactively"),
      bullet("Improves patient satisfaction and adherence through reduced medication costs"),
      bullet("Demonstrates physician value in medication cost optimization"),
      emptyLine(),

      h4("Implementation Considerations"),
      emptyLine(),
      bullet("Integration with PBM formulary databases for real-time coverage and pricing"),
      bullet("Specialty pharmacy partnerships for biologic dispensing and patient support"),
      bullet("Patient education materials on biosimilars and generics"),
      bullet("Pharmacy integration for therapeutic interchange notifications and counseling"),
      emptyLine(),

      // Summary
      h2("Summary"),
      emptyLine(),
      p("These primary care use cases demonstrate Cordance Health's potential to transform clinical decision support across preventive care, chronic disease management, and high-value care delivery. Each use case addresses all three pillars (Economics, Quality & Safety, Population Health), provides clear physician value through reduced cognitive burden and automated workflows, and is measurable with specific targets. The platform's ability to anticipate needs, provide context-aware recommendations, integrate seamlessly into workflow, and coordinate across the care ecosystem positions Cordance Health as a transformative solution for primary care's most pressing challenges."),
      emptyLine(),

      // References section
      h2("References"),
      emptyLine(),

      p("[1] Centers for Disease Control and Prevention. Colorectal Cancer Screening. https://www.cdc.gov/colorectal-cancer/screening/index.html"),
      emptyLine(),
      p("[2] Sabatino SA, et al. Cancer screening test receipt—United States, 2018. MMWR Morb Mortal Wkly Rep. 2021;70(2):29-35. https://www.cdc.gov/mmwr/volumes/70/wr/mm7002a1.htm"),
      emptyLine(),
      p("[3] Mariotto AB, et al. Medical Care Costs Associated with Cancer Survivorship in the United States. Cancer Epidemiol Biomarkers Prev. 2020;29(7):1304-1312. https://doi.org/10.1158/1055-9965.EPI-19-1534"),
      emptyLine(),
      p("[4] Doubeni CA, et al. Effectiveness of Screening Colonoscopy in Reducing the Risk of Death From Right and Left Colon Cancer: A Large Community-Based Study. Gut. 2018;67(2):291-298. https://doi.org/10.1136/gutjnl-2016-312712"),
      emptyLine(),
      p("[5] Maurer DM. Screening for Depression. Am Fam Physician. 2012;85(2):139-144. https://www.aafp.org/pubs/afp/issues/2012/0115/p139.html"),
      emptyLine(),
      p("[6] American Diabetes Association. Standards of Care in Diabetes—2025. Diabetes Care. 2025;48(Supplement_1). https://doi.org/10.2337/dc25-Sint"),
      emptyLine(),
      p("[7] Sattar N, et al. Cardiovascular, mortality, and kidney outcomes with GLP-1 receptor agonists in patients with type 2 diabetes: a systematic review and meta-analysis of randomised trials. Lancet Diabetes Endocrinol. 2021;9(10):653-662. https://doi.org/10.1016/S2213-8587(21)00203-5"),
      emptyLine(),
      p("[8] Chrvala CA, et al. Diabetes self-management education for adults with type 2 diabetes mellitus: A systematic review of the effect on glycemic control. Patient Educ Couns. 2016;99(6):926-943. https://doi.org/10.1016/j.pec.2015.11.003"),
      emptyLine(),
      p("[9] Sattar N, et al. Cardiovascular, mortality, and kidney outcomes with GLP-1 receptor agonists in patients with type 2 diabetes: a systematic review and meta-analysis of randomised trials. Lancet Diabetes Endocrinol. 2021;9(10):653-662. https://doi.org/10.1016/S2213-8587(21)00203-5"),
      emptyLine(),
      p("[10] Li Y, et al. All-Cause Costs for Common Chronic Conditions by CKD Stage. Am J Manag Care. 2017;23(8 Suppl):S145-S152. PMID: 28978205"),
      emptyLine(),
      p("[11] Sattar N, et al. Cardiovascular, mortality, and kidney outcomes with GLP-1 receptor agonists in patients with type 2 diabetes: a systematic review and meta-analysis of randomised trials. Lancet Diabetes Endocrinol. 2021;9(10):653-662. https://doi.org/10.1016/S2213-8587(21)00203-5"),
      emptyLine(),
      p("[12] McMurray JJV, et al. Dapagliflozin in Patients with Heart Failure and Reduced Ejection Fraction. N Engl J Med. 2019;381(21):1995-2008. https://doi.org/10.1056/NEJMoa1911303"),
      emptyLine(),
      p("[13] National Eye Institute. Diabetic Retinopathy. https://www.nei.nih.gov/learn-about-eye-health/eye-conditions-and-diseases/diabetic-retinopathy"),
      emptyLine(),
      p("[14] Centers for Disease Control and Prevention. Chronic Kidney Disease in the United States, 2023. https://www.cdc.gov/ckd"),
      emptyLine(),
      p("[15] Li Y, et al. All-Cause Costs for Common Chronic Conditions by CKD Stage. Am J Manag Care. 2017;23(8 Suppl):S145-S152. PMID: 28978205"),
      emptyLine(),
      p("[16] Heerspink HJL, et al. Dapagliflozin in Patients with Chronic Kidney Disease. N Engl J Med. 2020;383(15):1436-1446. https://doi.org/10.1056/NEJMoa2024816"),
      emptyLine(),
      p("[17] Heerspink HJL, et al. Dapagliflozin in Patients with Chronic Kidney Disease. N Engl J Med. 2020;383(15):1436-1446. https://doi.org/10.1056/NEJMoa2024816"),
      emptyLine(),
      p("[18] Heerspink HJL, et al. Dapagliflozin in Patients with Chronic Kidney Disease. N Engl J Med. 2020;383(15):1436-1446. https://doi.org/10.1056/NEJMoa2024816"),
      emptyLine(),
      p("[19] Li Y, et al. All-Cause Costs for Common Chronic Conditions by CKD Stage. Am J Manag Care. 2017;23(8 Suppl):S145-S152. PMID: 28978205"),
      emptyLine(),
      p("[20] Heerspink HJL, et al. Dapagliflozin in Patients with Chronic Kidney Disease. N Engl J Med. 2020;383(15):1436-1446. https://doi.org/10.1056/NEJMoa2024816"),
      emptyLine(),
      p("[21] Masnoon N, et al. What is polypharmacy? A systematic review of definitions. BMC Geriatr. 2017;17(1):230. https://doi.org/10.1186/s12877-017-0621-2"),
      emptyLine(),
      p("[22] American Geriatrics Society Beers Criteria Update Expert Panel. American Geriatrics Society 2023 updated AGS Beers Criteria for potentially inappropriate medication use in older adults. J Am Geriatr Soc. 2023;71(7):2052-2081. https://doi.org/10.1111/jgs.18372"),
      emptyLine(),
      p("[23] Ruxton K, et al. Drugs with anticholinergic effects and cognitive impairment, falls and all-cause mortality in older adults: A systematic review and meta-analysis. Br J Clin Pharmacol. 2021;87(6):2457-2480. https://doi.org/10.1111/bcp.14617"),
      emptyLine(),
      p("[24] Bentler SE, et al. The aftermath of hip fracture: discharge placement, functional status change, and mortality. Am J Epidemiol. 2009;170(10):1290-1299. https://doi.org/10.1093/aje/kwp266"),
      emptyLine(),
      p("[25] American Geriatrics Society Beers Criteria Update Expert Panel. American Geriatrics Society 2023 updated AGS Beers Criteria for potentially inappropriate medication use in older adults. J Am Geriatr Soc. 2023;71(7):2052-2081. https://doi.org/10.1111/jgs.18372"),
      emptyLine(),
      p("[26] Bentler SE, et al. The aftermath of hip fracture: discharge placement, functional status change, and mortality. Am J Epidemiol. 2009;170(10):1290-1299. https://doi.org/10.1093/aje/kwp266"),
      emptyLine(),
      p("[27] Budnitz DS, et al. Emergency hospitalizations for adverse drug events in older Americans. N Engl J Med. 2011;365(21):2002-2012. https://doi.org/10.1056/NEJMsa1103053"),
      emptyLine(),
      p("[28] Ruxton K, et al. Drugs with anticholinergic effects and cognitive impairment, falls and all-cause mortality in older adults: A systematic review and meta-analysis. Br J Clin Pharmacol. 2021;87(6):2457-2480. https://doi.org/10.1111/bcp.14617"),
      emptyLine(),
      p("[29] Gillespie LD, et al. Interventions for preventing falls in older people living in the community. Cochrane Database Syst Rev. 2012;(9):CD007146. https://doi.org/10.1002/14651858.CD007146.pub3"),
      emptyLine(),
      p("[30] ASPE. Social Determinants of Health: Evidence Review. US Department of Health and Human Services. https://aspe.hhs.gov/sites/default/files/documents/e2b650cd64cf84aae8ff0fae7474af82/SDOH-Evidence-Review.pdf"),
      emptyLine(),
      p("[31] Oronce CIA, et al. Association Between State-Level Income Inequality and COVID-19 Cases and Mortality in the USA. J Gen Intern Med. 2020;35(9):2791-2793. https://doi.org/10.1007/s11606-020-05971-3"),
      emptyLine(),
      p("[32] Billioux A, et al. Standardized Screening for Health-Related Social Needs in Clinical Settings: The Accountable Health Communities Screening Tool. NAM Perspectives. 2017. https://doi.org/10.31478/201705b"),
      emptyLine(),
      p("[33] Berkowitz SA, et al. Food insecurity and metabolic control among U.S. adults with diabetes. Diabetes Care. 2013;36(10):3093-3099. https://doi.org/10.2337/dc13-0570"),
      emptyLine(),
      p("[34] Centers for Disease Control and Prevention. Colorectal Cancer Screening. https://www.cdc.gov/colorectal-cancer/screening/index.html"),
      emptyLine(),
      p("[35] Corley DA, et al. Adenoma Detection Rate and Risk of Colorectal Cancer and Death. N Engl J Med. 2014;370(14):1298-1306. https://doi.org/10.1056/NEJMoa1309086"),
      emptyLine(),
      p("[36] USPSTF. Screening for Colorectal Cancer: US Preventive Services Task Force Recommendation Statement. JAMA. 2021;325(19):1965-1977. https://doi.org/10.1001/jama.2021.6238"),
      emptyLine(),
      p("[37] Ladabaum U, et al. Cost-Effectiveness and National Effects of Initiating Colorectal Cancer Screening for Average-Risk Persons at Age 45 Years Instead of 50 Years. Gastroenterology. 2019;157(1):137-148. https://doi.org/10.1053/j.gastro.2019.03.023"),
      emptyLine(),
      p("[38] Mariotto AB, et al. Medical Care Costs Associated with Cancer Survivorship in the United States. Cancer Epidemiol Biomarkers Prev. 2020;29(7):1304-1312. https://doi.org/10.1158/1055-9965.EPI-19-1534"),
      emptyLine(),
      p("[39] Doubeni CA, et al. Effectiveness of Screening Colonoscopy in Reducing the Risk of Death From Right and Left Colon Cancer: A Large Community-Based Study. Gut. 2018;67(2):291-298. https://doi.org/10.1136/gutjnl-2016-312712"),
      emptyLine(),
      p("[40] Emery DJ, et al. Overuse of Magnetic Resonance Imaging. JAMA Intern Med. 2013;173(9):823-825. https://doi.org/10.1001/jamainternmed.2013.3804"),
      emptyLine(),
      p("[41] Fritz JM, et al. Early Physical Therapy vs Usual Care in Patients With Recent-Onset Low Back Pain: A Randomized Clinical Trial. JAMA. 2015;314(14):1459-1467. https://doi.org/10.1001/jama.2015.11648"),
      emptyLine(),
      p("[42] Brinjikji W, et al. Systematic literature review of imaging features of spinal degeneration in asymptomatic populations. AJNR Am J Neuroradiol. 2015;36(4):811-816. https://doi.org/10.3174/ajnr.A4173"),
      emptyLine(),
      p("[43] Chou R, et al. Diagnosis and Treatment of Low Back Pain: A Joint Clinical Practice Guideline from the American College of Physicians and the American Pain Society. Ann Intern Med. 2007;147(7):478-491. https://doi.org/10.7326/0003-4819-147-7-200710020-00006"),
      emptyLine(),
      p("[44] Brinjikji W, et al. Systematic literature review of imaging features of spinal degeneration in asymptomatic populations. AJNR Am J Neuroradiol. 2015;36(4):811-816. https://doi.org/10.3174/ajnr.A4173"),
      emptyLine(),
      p("[45] Fritz JM, et al. Early Physical Therapy vs Usual Care in Patients With Recent-Onset Low Back Pain: A Randomized Clinical Trial. JAMA. 2015;314(14):1459-1467. https://doi.org/10.1001/jama.2015.11648"),
      emptyLine(),
      p("[46] Fritz JM, et al. Early Physical Therapy vs Usual Care in Patients With Recent-Onset Low Back Pain: A Randomized Clinical Trial. JAMA. 2015;314(14):1459-1467. https://doi.org/10.1001/jama.2015.11648"),
      emptyLine(),
      p("[47] Chou R, et al. Diagnostic Imaging for Low Back Pain: Advice for High-Value Health Care From the American College of Physicians. Ann Intern Med. 2011;154(3):181-189. https://doi.org/10.7326/0003-4819-154-3-201102010-00008"),
      emptyLine(),
      p("[48] Health Catalyst. 5 Ways to Improve HCC Coding Accuracy and Risk Adjustment. https://www.healthcatalyst.com/learn/insights/5-ways-improve-hcc-coding-accuracy-risk-adjustment"),
      emptyLine(),
      p("[49] RAAPID Inc. Risk Adjustment Coding Guidelines. https://www.raapidinc.com/blogs/risk-adjustment-coding-guidelines/"),
      emptyLine(),
      p("[50] MBW Revenue Cycle Management. The ABCs of a Risk Adjustment Factor (RAF) Score in HCC Coding. https://www.mbwrcm.com/the-revenue-cycle-blog/the-abcs-of-a-risk-adjustment-factor-raf-score-in-hcc-coding"),
      emptyLine(),
      p("[51] AAFP. Risk Adjustment Coding and HCC Coding: Getting Paid for What You Do. Fam Pract Manag. 2016;23(5):24-27. https://www.aafp.org/pubs/fpm/issues/2016/0900/p24.html"),
      emptyLine(),
      p("[52] Health Catalyst. HCC Risk Adjustment Coding: Allina Health Success Story. https://www.healthcatalyst.com/learn/success-stories/hcc-risk-adjustment-coding-allina-health"),
      emptyLine(),
      p("[53] RAAPID Inc. Risk Adjustment Coding Guidelines. https://www.raapidinc.com/blogs/risk-adjustment-coding-guidelines/"),
      emptyLine(),
      p("[54] Fleisher LA, et al. 2014 ACC/AHA Guideline on Perioperative Cardiovascular Evaluation and Management of Patients Undergoing Noncardiac Surgery. J Am Coll Cardiol. 2014;64(22):e77-e137. https://doi.org/10.1016/j.jacc.2014.07.944"),
      emptyLine(),
      p("[55] Lee TH, et al. Derivation and prospective validation of a simple index for prediction of cardiac risk of major noncardiac surgery. Circulation. 1999;100(10):1043-1049. https://doi.org/10.1161/01.CIR.100.10.1043"),
      emptyLine(),
      p("[56] Lee TH, et al. Derivation and prospective validation of a simple index for prediction of cardiac risk of major noncardiac surgery. Circulation. 1999;100(10):1043-1049. https://doi.org/10.1161/01.CIR.100.10.1043"),
      emptyLine(),
      p("[57] Fleisher LA, et al. 2014 ACC/AHA Guideline on Perioperative Cardiovascular Evaluation and Management of Patients Undergoing Noncardiac Surgery. J Am Coll Cardiol. 2014;64(22):e77-e137. https://doi.org/10.1016/j.jacc.2014.07.944"),
      emptyLine(),
      p("[58] Fleisher LA, et al. 2014 ACC/AHA Guideline on Perioperative Cardiovascular Evaluation and Management of Patients Undergoing Noncardiac Surgery. J Am Coll Cardiol. 2014;64(22):e77-e137. https://doi.org/10.1016/j.jacc.2014.07.944"),
      emptyLine(),
      p("[59] US Department of Health and Human Services. Fact Sheet: Bringing Lower-Cost Biosimilar Drugs to American Patients. https://www.hhs.gov/press-room/fact-sheet-bringing-lower-cost-biosimilar-drugs-to-american-patients.html"),
      emptyLine(),
      p("[60] RAND Corporation. Savings from Biosimilar Drugs. https://www.rand.org/content/dam/rand/pubs/perspectives/PE100/PE127/RAND_PE127.pdf"),
      emptyLine(),
      p("[61] FDA. Biosimilar and Interchangeable Biologics: More Treatment Choices. https://www.fda.gov/consumers/consumer-updates/biosimilar-and-interchangeable-biologics-more-treatment-choices"),
      emptyLine(),
      p("[62] AJMC. Understanding Interchangeable Biosimilars at the Federal and State Levels. https://www.ajmc.com/view/understanding-interchangeable-biosimilars-at-the-federal-and-state-levels"),
      emptyLine(),
      p("[63] World Health Organization. Biosimilars: Expanding Access to Essential Biologic Therapies. https://www.who.int/news/item/13-02-2025-biosimilars--expanding-access-to-essential-biologic-therapies"),
      emptyLine(),
      p("[64] RAND Corporation. Savings from Biosimilar Drugs. https://www.rand.org/content/dam/rand/pubs/perspectives/PE100/PE127/RAND_PE127.pdf"),
      emptyLine(),
      p("[65] FDA. Biosimilar and Interchangeable Biologics: More Treatment Choices. https://www.fda.gov/consumers/consumer-updates/biosimilar-and-interchangeable-biologics-more-treatment-choices"),
      emptyLine(),
      p("[66] FDA. Biosimilar and Interchangeable Biologics: More Treatment Choices. https://www.fda.gov/consumers/consumer-updates/biosimilar-and-interchangeable-biologics-more-treatment-choices"),
      emptyLine(),
      p("[67] AJMC. Understanding Interchangeable Biosimilars at the Federal and State Levels. https://www.ajmc.com/view/understanding-interchangeable-biosimilars-at-the-federal-and-state-levels"),
      emptyLine(),

      emptyLine()
    ]
  }]
});

// Save the document
const fileName = 'docs/Cordance/Cordance_Health_Insights_Bank_Primary_Care.docx';

require('docx').Packer.toBuffer(doc).then(buffer => {
  fs.writeFileSync(fileName, buffer);
  console.log(`Document created successfully: ${fileName}`);
});
