"""
Compare OLD vs NEW suffix variation generation to demonstrate the fix.

This shows what variations were generated BEFORE the fix (only suffixes on last word)
vs AFTER the fix (suffixes on any word).
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from src.concordance.hebrew_text_processor import split_words

# Common Hebrew pronominal suffixes
PRONOMINAL_SUFFIXES = ['י', 'ך', 'ו', 'ה', 'נו', 'כם', 'כן', 'הם', 'הן']
PREPOSITIONS = {'ב': 'in/with', 'כ': 'like/as', 'ל': 'to/for', 'מ': 'from'}

def old_suffix_variations(words):
    """OLD behavior: only add suffixes to LAST word."""
    variations = set()

    if len(words) < 2:
        return variations

    # OLD: Only last word gets suffixes
    for suffix in PRONOMINAL_SUFFIXES:
        modified_words = words[:-1] + [words[-1] + suffix]
        variation = ' '.join(modified_words)
        variations.add(variation)

        # With preposition on first word
        for prep in PREPOSITIONS:
            modified_words_with_prep = [prep + words[0]] + words[1:-1] + [words[-1] + suffix]
            variations.add(' '.join(modified_words_with_prep))

    return variations


def new_suffix_variations(words):
    """NEW behavior: add suffixes to ANY word."""
    variations = set()

    if len(words) < 2:
        return variations

    # NEW: Each word can get a suffix
    for word_idx in range(len(words)):
        for suffix in PRONOMINAL_SUFFIXES:
            modified_words = words.copy()
            modified_words[word_idx] = words[word_idx] + suffix
            variation = ' '.join(modified_words)
            variations.add(variation)

            # Also with prepositions on first word
            if word_idx > 0:
                for prep in PREPOSITIONS:
                    prefixed_words = [prep + words[0]] + modified_words[1:]
                    variations.add(' '.join(prefixed_words))

            elif word_idx == 0:
                for prep in PREPOSITIONS:
                    prefixed_words = [prep + modified_words[0]] + modified_words[1:]
                    variations.add(' '.join(prefixed_words))

    return variations


def compare_suffix_generation():
    """Compare OLD vs NEW suffix generation for test phrase."""

    print("=" * 80)
    print("Suffix Variation Generation: OLD vs NEW")
    print("=" * 80)

    test_phrase = "הר קדש"
    words = split_words(test_phrase)

    print(f"\nTest phrase: {test_phrase}")
    print(f"Words: {words}")

    # Generate with OLD method
    old_vars = old_suffix_variations(words)

    # Generate with NEW method
    new_vars = new_suffix_variations(words)

    print(f"\n{'OLD Method':<40} {'NEW Method':<40}")
    print(f"{'(suffix on last word only)':<40} {'(suffix on any word)':<40}")
    print("-" * 80)
    print(f"Total variations: {len(old_vars):<28} Total variations: {len(new_vars)}")
    print()

    # Show what's NEW (not in old)
    only_in_new = new_vars - old_vars

    print(f"\n{len(only_in_new)} NEW variations not generated by old method:")
    print("-" * 80)

    # Categorize the new variations
    suffix_on_first = []
    suffix_on_both = []
    other = []

    for var in only_in_new:
        var_words = split_words(var)
        if len(var_words) >= 2:
            # Check if first word has suffix (by checking if it's longer than original)
            first_has_suffix = False
            second_has_suffix = False

            for suffix in PRONOMINAL_SUFFIXES:
                if var_words[0].endswith(suffix) or var_words[0].replace('ב', '').replace('כ', '').replace('ל', '').replace('מ', '').endswith(suffix):
                    first_has_suffix = True
                if var_words[1].endswith(suffix):
                    second_has_suffix = True

            # Check against original words
            if words[0] in var_words[0] or var_words[0].replace('ב', '').replace('כ', '').replace('ל', '').replace('מ', '') == words[0]:
                # First word is base, second has suffix (OLD behavior)
                pass
            else:
                # First word has modification
                if second_has_suffix:
                    suffix_on_both.append(var)
                else:
                    suffix_on_first.append(var)

    print(f"\n1. Suffixes on FIRST word only ({len(suffix_on_first)} variations):")
    for var in sorted(suffix_on_first)[:10]:
        print(f"   {var}")
    if len(suffix_on_first) > 10:
        print(f"   ... and {len(suffix_on_first) - 10} more")

    print(f"\n2. Suffixes on BOTH words ({len(suffix_on_both)} variations):")
    for var in sorted(suffix_on_both)[:10]:
        print(f"   {var}")
    if len(suffix_on_both) > 10:
        print(f"   ... and {len(suffix_on_both) - 10} more")

    # Key examples
    print("\n" + "=" * 80)
    print("KEY EXAMPLE: Why this fix matters")
    print("=" * 80)

    target_var = "בהר קדשך"

    print(f"\nTarget variation: {target_var}")
    print(f"  Meaning: 'in your holy mountain'")
    print(f"  Found in: Psalm 15:1")
    print()
    print(f"  OLD method generates this? {target_var in old_vars}")
    print(f"  NEW method generates this? {target_var in new_vars}")
    print()

    if target_var in new_vars and target_var not in old_vars:
        print("✓ SUCCESS! The new method fixes the search!")
        print(f"  OLD: Would NOT find Psalm 15:1 when searching 'הר קדש'")
        print(f"  NEW: WILL find Psalm 15:1 when searching 'הר קדש'")
    else:
        print("✗ Something is wrong with the comparison")

    # Show breakdown of the target variation
    print(f"\n  Breakdown of '{target_var}':")
    print(f"    'ב' = preposition (in/with)")
    print(f"    'הר' = mountain")
    print(f"    'קדש' = holy")
    print(f"    'ך' = suffix (your)")
    print(f"    Combined: 'in' + 'mountain' + 'holy' + 'your' = 'in your holy mountain'")


if __name__ == '__main__':
    # Ensure UTF-8 encoding on Windows
    if sys.platform == 'win32':
        sys.stdout.reconfigure(encoding='utf-8')

    compare_suffix_generation()
